# disable autofixing PRs, commenting "pre-commit.ci autofix" on a pull request triggers a autofix
ci:
    autofix_prs: false
exclude: ^(versioneer.py|constructor/_version.py|CONSTRUCT.md|docs/source/construct-yaml.md)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2700fd5671c633760d912769c041bfcde2b9a01b  # frozen: v0.15.22
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95  # frozen: v0.11.0.1
    hooks:
      - id: shellcheck
        exclude: ^(constructor/header.sh|constructor/osx/.*sh)
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 1a4bb160cab6417b3045e1b37b6b72449243e658  # frozen: 0.37.4
    hooks:
      - id: check-github-workflows
