IF DEFINED UNINSTALLER_REMOVE_USER_DATA (
  DEL "%USER_FILES%\data"
)
IF DEFINED UNINSTALLER_REMOVE_CACHES (
  DEL "%USER_FILES%\cache"
)
IF DEFINED UNINSTALLER_REMOVE_CONFIG_FILES (
  IF "%UNINSTALLER_REMOVE_CONFIG_FILES%" NEQ "user" (
    DEL "%USER_FILES%\config_system"
  )
  IF "%UNINSTALLER_REMOVE_CONFIG_FILES%" NEQ "system" (
    DEL "%USER_FILES%\config_user"
  )
)
