{% set data = load_setup_py_data() %}

package:
  name: constructor
  version: {{ data.get('version') }}

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only
  #    captures committed code, so pay attention.
  - git_url: ../

build:
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - constructor = constructor.main:main

requirements:
  host:
    - python
    - pip
  run:
    - conda >=4.6
    - python
    - ruamel_yaml >=0.11.14,<0.16
    - conda-standalone
    - pillow >=3.1     # [win]
    - nsis >=3.01      # [win]

test:
  source_files:
    - scripts
    - examples
    - .coveragerc
  requires:
    - pillow >=3.1
    - pytest
  commands:
    - constructor -V
    - pytest --pyargs -v constructor
    - python scripts/run_examples.py

about:
  home: https://conda.io
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
    - kalefranz
    - msarahan
    - mingwandroid
    - nehaljwani
    - mcg1969
